title: musings
description: "A personal blog about tech, self-hosting, and experiments"
lang: en
url: "https://rainma.ker.life"
baseurl: ""

author: cw_l
linkedin_username: leechengwei
twitter_username: cw_l
github_username: cw-l

timezone: Asia/Singapore
permalink: /:year/:month/:day/:title/

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
paginate: 5
paginate_path: "/posts/page:num/"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
